# External gems
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

# Site settings
title: Adam Casey
subtitle: "Software Developer, Computer Science Student. Based in the UK."
email: adamncasey@gmail.com
name: Adam Casey
description: >
  Software Developer, Computer Science Student. Based in the UK.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://Dotmister.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: Twitter
    icon: twitter
    username: "@AdamN_Casey"
    url: https://twitter.com/AdamN_Casey
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - name: GitHub
    icon: github
    username: Dotmister
    url: https://github.com/Dotmister
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin
    username: Adam Casey
    url: https://www.linkedin.com/in/adamncasey
    desc: Connect with me on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: ?mini=true
    share_link: "&amp;url="

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"
